flags:
  texmath:
    network-uri: true
    executable: true
packages:
- '.'
extra-deps:
- git: https://github.com/jgm/pandoc-types.git
  commit: fd17cdc8acff3dc5cf54e9b2c1d418c6dc350d7d
resolver: lts-18.10
