name: CI tests

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - ghc: '8.10'
            cabal: '3.2'
          - ghc: '9.2'
            cabal: '3.4'
          - ghc: '9.4'
            cabal: 'latest'
          - ghc: '9.6'
            cabal: 'latest'
          - ghc: '9.8'
            cabal: 'latest'
          - ghc: '9.10'
            cabal: 'latest'
    steps:
    - uses: actions/checkout@v4
    - name: Install cabal/ghc
      run: |
        ghcup install ghc --set ${{ matrix.versions.ghc }}
        ghcup install cabal --set ${{ matrix.versions.cabal }}

    - name: Cache cabal global package db
      id:   cabal-global
      uses: actions/cache@v4
      with:
        path: |
          ~/.cabal
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-global-${{ secrets.CACHE_VERSION }}

    - name: Cache cabal work
      id:   cabal-local
      uses: actions/cache@v4
      with:
        path: |
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-local-${{ secrets.CACHE_VERSION }}

    - name: Install dependencies
      run: |
          cabal v2-update
          cabal v2-build --dependencies-only --enable-tests --disable-optimization -fexecutable all
    - name: Build and test
      run: |
          cabal v2-build --enable-tests --disable-optimization -fexecutable all
          cabal v2-test --disable-optimization all

  linux-stack:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4

    # declare/restore cached things
    - name: Cache stack global package db
      id:   stack-global
      uses: actions/cache@v4
      with:
        path: |
          ~/.stack
        key: ${{ runner.os }}-stack-global-${{ secrets.CACHE_VERSION }}

    - name: Cache stack work
      id:   stack-local
      uses: actions/cache@v4
      with:
        path: |
          .stack-work
        key: ${{ runner.os }}-stack-local-${{ secrets.CACHE_VERSION }}

    - name: Build and test
      run: |
          stack test --fast


# macos:

#   runs-on: macOS-latest

#   steps:
#   - uses: actions/checkout@v4
#   - name: Install stack
#     run: |
#         curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz -o stack.tar.gz
#         tar xzvf stack.tar.gz --strip-components=1 'stack*/stack'
#   - name: Install dependencies
#     run: |
#         ./stack update
#         ./stack test --dependencies-only --fast
#   - name: Build and test
#     run: |
#         ./stack install --fast --test --haddock --no-haddock-deps
