name: CI tests

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - ghc: '9.6'
            cabal: 'latest'
    steps:
    - uses: actions/checkout@v1
    - name: Install cabal/ghc
      run: |
        ghcup install ghc --set ${{ matrix.versions.ghc }}
        ghcup install cabal --set ${{ matrix.versions.cabal }}

    - name: Cache cabal global package db
      id:   cabal-global
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-global-${{ secrets.CACHE_VERSION }}

    - name: Cache cabal work
      id:   cabal-local
      uses: actions/cache@v3
      with:
        path: |
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-local-${{ secrets.CACHE_VERSION }}

    - name: Install dependencies
      run: |
          cabal v2-update
          cabal v2-build --dependencies-only --enable-tests --disable-optimization -fexecutable all
    - name: Build and test
      run: |
          cabal v2-build --enable-tests --disable-optimization -fexecutable all
          cabal v2-test --disable-optimization all
          stack install --flag texmath:server
    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: texmath-server
        path: /home/runner/.local/bin/texmath-server
        
